name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set execute permission for configure
      run: chmod +x configure
    - name: Set up Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libc6-dev
    - name: Run configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
